 language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
 script:
   - yarn test
 env:
   - CI=true

 before_deploy:
   - yarn run build

 deploy:
   provider: script
   script: ''
   skip_cleanup: true
   on:
     branch: master
