 language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
 script:
   - yarn travis
 env:
   - CI=true

 notifications:
    slack: jmelnick:pKSMAuivv7MPfyHou5p3YBXG

 before_deploy:
   - yarn run build
 deploy:
   provider: script
   script: ''
   skip_cleanup: true
   on:
     branch: master
