 language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
 script:
   - yarn travis
 env:
   - CI=true

 notifications:
    slack: GetOrganizationKeyFrom : https://jmelnick.slack.com/apps/A0F81FP4N-travis-ci

 before_deploy:
   - yarn run build
 deploy:
   provider: script
   script: ''
   skip_cleanup: true
   on:
     branch: master
